### PR TITLE
SQLite hacks

### PR DESCRIPTION
**Pull request by netshade**
Submitting this PR, but not intending to merge. I merged master into `feature/sqlite`, and then just wanted to see if I could get the app to run in SQLite with some changes. It seems like things are working fine, thought you might like to try it out. I got excited about the idea of no / nearly no distributed dependencies. :)

### CODE REVIEW

**Comment by netshade** [comment]
Updated this to allow for Postgres and Sqlite to have a better abstraction interface between the two, as well as adding some conveniences in both `setup` and `run`, such that when running the application the desired cargo compilation path is inferred via the `DATABASE_URI`. Had to make some adjustments such that `cargo watch` would continue to be right, but now you can edit the `.env` file and the server will restart with the right DB backend and the right thing will just happen.

**Comment by netshade** [comment]
Fingers crossed but I think the test suite will pass now.

**Comment by netshade** [comment]
In order to get the tests to run, I had to strip out the `infer_schema` package and add something that will generate the schema at `setup` time. Diesel is deprecating `infer_schema` anyways, so it seemed like the right move - however, admittedly, I am sort of going crazy in this PR-to-a-PR. Sorry for being silly over here.

**Comment by hannahwhy** [comment]
Huh, I didn't get a notification for these changes.  I should fix that.

Thanks for poking at this! I think I get the gist of the changes, though it will take some time to understand them.  I think the earliest I could do that is late Monday evening (CDT) or Tuesday.

Having said that, I don't see a reason to not merge this: it catches up with upstream and it looks like you've done some more database abstraction that I would have needed to do anyway.  When it's proposed for a PR upstream it'll get more review there also.

**Comment by netshade** [comment]
Awesome, thanks!

**Pull request merged**
